# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 00:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField()),
                ('url', models.TextField()),
                ('querystring', models.TextField()),
                ('action', models.TextField()),
                ('http_code', models.TextField()),
                ('http_referrer', models.TextField()),
                ('user_agent', models.TextField()),
                ('ip', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post_content', models.TextField(default=b'')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True)),
                ('action', models.TextField(blank=True)),
                ('http_referrer', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
                'get_latest_by': 'timestamp',
                'managed': True,
            },
        ),
    ]
