# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 22:53


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('big_brother', '0002_auto_20170519_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
