# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 00:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnophelesSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anopheles', models.TextField()),
                ('gvi_anophelesParams', models.TextField(blank=True, null=True)),
                ('itn_anophelesParams', models.TextField(blank=True, null=True)),
                ('irs_anophelesParams', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaselineScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('xml', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DemographicsSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('maximum_age_yrs', models.CharField(max_length=200)),
                ('xml', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InterventionComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InterventionSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('xml', models.TextField()),
                ('documentation_url', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ts_om.InterventionComponent')),
            ],
        ),
        migrations.CreateModel(
            name='ModelSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('xml', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml', models.TextField()),
                ('start_date', models.IntegerField(default=2016)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('baseline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ts_om.BaselineScenario')),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.TextField(default=b'32')),
                ('status', models.TextField(choices=[(b'New', b'New'), (b'Submitted', b'Submitted'), (b'Running', b'Running'), (b'Complete', b'Complete'), (b'Failed', b'Failed')], default=b'New')),
                ('pid', models.TextField(default=b'')),
                ('cwd', models.TextField(default=b'')),
                ('input_file', models.FileField(blank=True, null=True, upload_to=b'files/%Y/%m/')),
                ('output_file', models.FileField(blank=True, null=True, upload_to=b'files/%Y/%m/')),
                ('ctsout_file', models.FileField(blank=True, null=True, upload_to=b'files/%Y/%m/')),
                ('model_stdout', models.FileField(blank=True, null=True, upload_to=b'files/%Y/%m/')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_error_message', models.TextField(default=b'')),
            ],
            options={
                'db_table': 'simulation',
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='new_simulation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scenario', to='ts_om.Simulation'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
