# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts_om', '0006_interventionsnippet_documentation_url'),
        ('ts_om', 'load_fixtures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentfile',
            name='sim_group',
        ),
        migrations.RemoveField(
            model_name='experimentfile',
            name='test_sim_group',
        ),
        migrations.RemoveField(
            model_name='experimentfile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExperimentFile',
        ),
    ]
