# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts_om', '0007_auto_20170713_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='sim_group',
        ),
        migrations.RemoveField(
            model_name='sweeparmmappingtoscenario',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='sweeparmmappingtoscenario',
            name='scenario',
        ),
        migrations.DeleteModel(
            name='Experiment',
        ),
        migrations.DeleteModel(
            name='SweepArmMappingToScenario',
        ),
    ]
