# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 14:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts_om', '0007_auto_20170713_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionsnippet',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ts_om.InterventionComponent'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='baseline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ts_om.BaselineScenario'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='new_simulation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scenario', to='ts_om.Simulation'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
